'use strict';

/* Jersey art registry -- see file header comment (unchanged from before this
   batch) for the full explanation of shape/usage. Generated from the 31
   'Top 20 All-Time Players' team grids uploaded to jerseys/source-grids/;
   tier is a first pass (team-internal rank position, with a short list of
   ~14 true inner-circle legends bumped to diamond) -- review and adjust via
   Admin -> Jerseys' Reclassify tool, it's a starting point, not gospel. */
const JERSEY_ART = {
  ANA: [
    { name: 'Selanne — #8', image: 'jerseys/ana-selanne-8.png', tier: 'amethyst' },
    { name: 'Kariya — #9', image: 'jerseys/ana-kariya-9.png', tier: 'amethyst' },
    { name: 'Niedermayer — #27', image: 'jerseys/ana-niedermayer-27.png', tier: 'ruby' },
    { name: 'Pronger — #44', image: 'jerseys/ana-pronger-44.png', tier: 'ruby' },
    { name: 'Giguere — #35', image: 'jerseys/ana-giguere-35.png', tier: 'ruby' },
    { name: 'Getzlaf — #15', image: 'jerseys/ana-getzlaf-15.png', tier: 'emerald' },
    { name: 'Perry — #10', image: 'jerseys/ana-perry-10.png', tier: 'emerald' },
    { name: 'Kesler — #17', image: 'jerseys/ana-kesler-17.png', tier: 'emerald' },
    { name: 'Beauchemin — #23', image: 'jerseys/ana-beauchemin-23.png', tier: 'emerald' },
    { name: 'Rucchin — #20', image: 'jerseys/ana-rucchin-20.png', tier: 'emerald' },
    { name: 'Oates — #77', image: 'jerseys/ana-oates-77.png', tier: 'gold' },
    { name: 'Salei — #24', image: 'jerseys/ana-salei-24.png', tier: 'gold' },
    { name: 'Lindholm — #47', image: 'jerseys/ana-lindholm-47.png', tier: 'gold' },
    { name: 'Fowler — #4', image: 'jerseys/ana-fowler-4.png', tier: 'gold' },
    { name: 'McDonald — #19', image: 'jerseys/ana-mcdonald-19.png', tier: 'gold' },
    { name: 'Cogliano — #7', image: 'jerseys/ana-cogliano-7.png', tier: 'silver' },
    { name: 'Pahlsson — #26', image: 'jerseys/ana-pahlsson-26.png', tier: 'silver' },
    { name: 'Moen — #12', image: 'jerseys/ana-moen-12.png', tier: 'silver' },
    { name: 'Gibson — #36', image: 'jerseys/ana-gibson-36.png', tier: 'silver' },
    { name: 'Hiller — #1', image: 'jerseys/ana-hiller-1.png', tier: 'silver' },
  ],
  BOS: [
    { name: 'Orr — #4', image: 'jerseys/bos-orr-4.png', tier: 'diamond' },
    { name: 'Bourque — #77', image: 'jerseys/bos-bourque-77.png', tier: 'amethyst' },
    { name: 'Esposito — #7', image: 'jerseys/bos-esposito-7.png', tier: 'ruby' },
    { name: 'Bergeron — #37', image: 'jerseys/bos-bergeron-37.png', tier: 'ruby' },
    { name: 'Chara — #33', image: 'jerseys/bos-chara-33.png', tier: 'ruby' },
    { name: 'Bucyk — #9', image: 'jerseys/bos-bucyk-9.png', tier: 'emerald' },
    { name: 'Schmidt — #15', image: 'jerseys/bos-schmidt-15.png', tier: 'emerald' },
    { name: 'O\'Reilly — #24', image: 'jerseys/bos-o-reilly-24.png', tier: 'emerald' },
    { name: 'Neely — #8', image: 'jerseys/bos-neely-8.png', tier: 'emerald' },
    { name: 'Middleton — #12', image: 'jerseys/bos-middleton-12.png', tier: 'emerald' },
    { name: 'Cashman — #12', image: 'jerseys/bos-cashman-12.png', tier: 'gold' },
    { name: 'Hodge — #8', image: 'jerseys/bos-hodge-8.png', tier: 'gold' },
    { name: 'Marchand — #63', image: 'jerseys/bos-marchand-63.png', tier: 'gold' },
    { name: 'Pastrnak — #88', image: 'jerseys/bos-pastrnak-88.png', tier: 'gold' },
    { name: 'McAvoy — #73', image: 'jerseys/bos-mcavoy-73.png', tier: 'gold' },
    { name: 'Cheevers — #6', image: 'jerseys/bos-cheevers-6.png', tier: 'silver' },
    { name: 'T. Thomas — #30', image: 'jerseys/bos-t-thomas-30.png', tier: 'silver' },
    { name: 'Rask — #40', image: 'jerseys/bos-rask-40.png', tier: 'silver' },
    { name: 'Sweeney — #32', image: 'jerseys/bos-sweeney-32.png', tier: 'silver' },
    { name: 'Clapper — #5', image: 'jerseys/bos-clapper-5.png', tier: 'silver' },
  ],
  BUF: [
    { name: 'Perreault — #11', image: 'jerseys/buf-perreault-11.png', tier: 'amethyst' },
    { name: 'Hasek — #39', image: 'jerseys/buf-hasek-39.png', tier: 'diamond' },
    { name: 'Lafontaine — #16', image: 'jerseys/buf-lafontaine-16.png', tier: 'ruby' },
    { name: 'Martin — #7', image: 'jerseys/buf-martin-7.png', tier: 'ruby' },
    { name: 'Robert — #8', image: 'jerseys/buf-robert-8.png', tier: 'ruby' },
    { name: 'Housley — #6', image: 'jerseys/buf-housley-6.png', tier: 'emerald' },
    { name: 'Gare — #18', image: 'jerseys/buf-gare-18.png', tier: 'emerald' },
    { name: 'Andreychuk — #25', image: 'jerseys/buf-andreychuk-25.png', tier: 'emerald' },
    { name: 'Mogilny — #89', image: 'jerseys/buf-mogilny-89.png', tier: 'emerald' },
    { name: 'Ramsay — #14', image: 'jerseys/buf-ramsay-14.png', tier: 'emerald' },
    { name: 'Vanek — #26', image: 'jerseys/buf-vanek-26.png', tier: 'gold' },
    { name: 'Miller — #30', image: 'jerseys/buf-miller-30.png', tier: 'gold' },
    { name: 'Pominville — #29', image: 'jerseys/buf-pominville-29.png', tier: 'gold' },
    { name: 'Briere — #48', image: 'jerseys/buf-briere-48.png', tier: 'gold' },
    { name: 'Drury — #23', image: 'jerseys/buf-drury-23.png', tier: 'gold' },
    { name: 'Afinogenov — #61', image: 'jerseys/buf-afinogenov-61.png', tier: 'silver' },
    { name: 'Foligno — #17', image: 'jerseys/buf-foligno-17.png', tier: 'silver' },
    { name: 'Audette — #20', image: 'jerseys/buf-audette-20.png', tier: 'silver' },
    { name: 'Korab — #4', image: 'jerseys/buf-korab-4.png', tier: 'silver' },
    { name: 'McKee — #74', image: 'jerseys/buf-mckee-74.png', tier: 'silver' },
  ],
  CGY: [
    { name: 'Iginla — #12', image: 'jerseys/cgy-iginla-12.png', tier: 'amethyst' },
    { name: 'Kiprusoff — #34', image: 'jerseys/cgy-kiprusoff-34.png', tier: 'amethyst' },
    { name: 'Giordano — #5', image: 'jerseys/cgy-giordano-5.png', tier: 'ruby' },
    { name: 'McDonald — #9', image: 'jerseys/cgy-mcdonald-9.png', tier: 'ruby' },
    { name: 'MacInnis — #2', image: 'jerseys/cgy-macinnis-2.png', tier: 'ruby' },
    { name: 'Vernon — #30', image: 'jerseys/cgy-vernon-30.png', tier: 'emerald' },
    { name: 'Fleury — #14', image: 'jerseys/cgy-fleury-14.png', tier: 'emerald' },
    { name: 'Nieuwendyk — #25', image: 'jerseys/cgy-nieuwendyk-25.png', tier: 'emerald' },
    { name: 'Loob — #16', image: 'jerseys/cgy-loob-16.png', tier: 'emerald' },
    { name: 'Roberts — #10', image: 'jerseys/cgy-roberts-10.png', tier: 'emerald' },
    { name: 'Nilsson — #14', image: 'jerseys/cgy-nilsson-14.png', tier: 'gold' },
    { name: 'Regehr — #28', image: 'jerseys/cgy-regehr-28.png', tier: 'gold' },
    { name: 'Makarov — #22', image: 'jerseys/cgy-makarov-22.png', tier: 'gold' },
    { name: 'Gaudreau — #13', image: 'jerseys/cgy-gaudreau-13.png', tier: 'gold' },
    { name: 'Bure — #13', image: 'jerseys/cgy-bure-13.png', tier: 'gold' },
    { name: 'Otto — #29', image: 'jerseys/cgy-otto-29.png', tier: 'silver' },
    { name: 'Conroy — #22', image: 'jerseys/cgy-conroy-22.png', tier: 'silver' },
    { name: 'Lindholm — #28', image: 'jerseys/cgy-lindholm-28.png', tier: 'silver' },
    { name: 'Backlund — #11', image: 'jerseys/cgy-backlund-11.png', tier: 'silver' },
    { name: 'Suter — #20', image: 'jerseys/cgy-suter-20.png', tier: 'silver' },
  ],
  CAR: [
    { name: 'Brind\'Amour — #17', image: 'jerseys/car-brind-amour-17.png', tier: 'amethyst' },
    { name: 'Ward — #30', image: 'jerseys/car-ward-30.png', tier: 'amethyst' },
    { name: 'Eric Staal — #12', image: 'jerseys/car-eric-staal-12.png', tier: 'ruby' },
    { name: 'Aho — #20', image: 'jerseys/car-aho-20.png', tier: 'ruby' },
    { name: 'Slavin — #74', image: 'jerseys/car-slavin-74.png', tier: 'ruby' },
    { name: 'Ron Francis — #10', image: 'jerseys/car-ron-francis-10.png', tier: 'emerald' },
    { name: 'Svechnikov — #37', image: 'jerseys/car-svechnikov-37.png', tier: 'emerald' },
    { name: 'Jordan Staal — #11', image: 'jerseys/car-jordan-staal-11.png', tier: 'emerald' },
    { name: 'Teravainen — #86', image: 'jerseys/car-teravainen-86.png', tier: 'emerald' },
    { name: 'Hamilton — #19', image: 'jerseys/car-hamilton-19.png', tier: 'emerald' },
    { name: 'O\'Neill — #92', image: 'jerseys/car-o-neill-92.png', tier: 'gold' },
    { name: 'Cole — #26', image: 'jerseys/car-cole-26.png', tier: 'gold' },
    { name: 'Ruutu — #15', image: 'jerseys/car-ruutu-15.png', tier: 'gold' },
    { name: 'Pesce — #22', image: 'jerseys/car-pesce-22.png', tier: 'gold' },
    { name: 'Necas — #88', image: 'jerseys/car-necas-88.png', tier: 'gold' },
    { name: 'Martinook — #48', image: 'jerseys/car-martinook-48.png', tier: 'silver' },
    { name: 'Mrazek — #34', image: 'jerseys/car-mrazek-34.png', tier: 'silver' },
    { name: 'Trocheck — #16', image: 'jerseys/car-trocheck-16.png', tier: 'silver' },
    { name: 'Jokinen — #21', image: 'jerseys/car-jokinen-21.png', tier: 'silver' },
    { name: 'Gleason — #6', image: 'jerseys/car-gleason-6.png', tier: 'silver' },
  ],
  CHI: [
    { name: 'Mikita — #17', image: 'jerseys/chi-mikita-17.png', tier: 'diamond' },
    { name: 'Hull — #89', image: 'jerseys/chi-hull-89.png', tier: 'amethyst' },
    { name: 'Hall — #1', image: 'jerseys/chi-hall-1.png', tier: 'ruby' },
    { name: 'Pilote — #3', image: 'jerseys/chi-pilote-3.png', tier: 'ruby' },
    { name: 'Toews — #19', image: 'jerseys/chi-toews-19.png', tier: 'ruby' },
    { name: 'Kane — #88', image: 'jerseys/chi-kane-88.png', tier: 'emerald' },
    { name: 'Savard — #18', image: 'jerseys/chi-savard-18.png', tier: 'emerald' },
    { name: 'Esposito — #35', image: 'jerseys/chi-esposito-35.png', tier: 'emerald' },
    { name: 'Chelios — #7', image: 'jerseys/chi-chelios-7.png', tier: 'emerald' },
    { name: 'Hossa — #81', image: 'jerseys/chi-hossa-81.png', tier: 'emerald' },
    { name: 'Larmer — #28', image: 'jerseys/chi-larmer-28.png', tier: 'gold' },
    { name: 'Belfour — #30', image: 'jerseys/chi-belfour-30.png', tier: 'gold' },
    { name: 'Keith — #2', image: 'jerseys/chi-keith-2.png', tier: 'gold' },
    { name: 'McDonald — #20', image: 'jerseys/chi-mcdonald-20.png', tier: 'gold' },
    { name: 'Wilson — #24', image: 'jerseys/chi-wilson-24.png', tier: 'gold' },
    { name: 'Roenick — #97', image: 'jerseys/chi-roenick-97.png', tier: 'silver' },
    { name: 'Crawford — #50', image: 'jerseys/chi-crawford-50.png', tier: 'silver' },
    { name: 'Magnuson — #3', image: 'jerseys/chi-magnuson-3.png', tier: 'silver' },
    { name: 'Secord — #12', image: 'jerseys/chi-secord-12.png', tier: 'silver' },
    { name: 'Sharp — #10', image: 'jerseys/chi-sharp-10.png', tier: 'silver' },
  ],
  COL: [
    { name: 'Sakic — #19', image: 'jerseys/col-sakic-19.png', tier: 'diamond' },
    { name: 'Forsberg — #21', image: 'jerseys/col-forsberg-21.png', tier: 'amethyst' },
    { name: 'Roy — #33', image: 'jerseys/col-roy-33.png', tier: 'diamond' },
    { name: 'Bourque — #77', image: 'jerseys/col-bourque-77.png', tier: 'ruby' },
    { name: 'Blake — #4', image: 'jerseys/col-blake-4.png', tier: 'ruby' },
    { name: 'Foote — #52', image: 'jerseys/col-foote-52.png', tier: 'emerald' },
    { name: 'Hejduk — #23', image: 'jerseys/col-hejduk-23.png', tier: 'emerald' },
    { name: 'Ozolinsh — #8', image: 'jerseys/col-ozolinsh-8.png', tier: 'emerald' },
    { name: 'Kamensky — #13', image: 'jerseys/col-kamensky-13.png', tier: 'emerald' },
    { name: 'Deadmarsh — #11', image: 'jerseys/col-deadmarsh-11.png', tier: 'emerald' },
    { name: 'MacKinnon — #29', image: 'jerseys/col-mackinnon-29.png', tier: 'gold' },
    { name: 'Makar — #8', image: 'jerseys/col-makar-8.png', tier: 'gold' },
    { name: 'Rantanen — #96', image: 'jerseys/col-rantanen-96.png', tier: 'gold' },
    { name: 'Landeskog — #92', image: 'jerseys/col-landeskog-92.png', tier: 'gold' },
    { name: 'Tanguay — #40', image: 'jerseys/col-tanguay-40.png', tier: 'gold' },
    { name: 'Drury — #37', image: 'jerseys/col-drury-37.png', tier: 'silver' },
    { name: 'Kadri — #91', image: 'jerseys/col-kadri-91.png', tier: 'silver' },
    { name: 'Lehkonen — #62', image: 'jerseys/col-lehkonen-62.png', tier: 'silver' },
    { name: 'Toews — #7', image: 'jerseys/col-toews-7.png', tier: 'silver' },
    { name: 'Nichushkin — #13', image: 'jerseys/col-nichushkin-13.png', tier: 'silver' },
  ],
  CBJ: [
    { name: 'Nash — #61', image: 'jerseys/cbj-nash-61.png', tier: 'amethyst' },
    { name: 'Atkinson — #13', image: 'jerseys/cbj-atkinson-13.png', tier: 'amethyst' },
    { name: 'Bobrovsky — #72', image: 'jerseys/cbj-bobrovsky-72.png', tier: 'ruby' },
    { name: 'Jones — #3', image: 'jerseys/cbj-jones-3.png', tier: 'ruby' },
    { name: 'Savard — #58', image: 'jerseys/cbj-savard-58.png', tier: 'ruby' },
    { name: 'Foligno — #71', image: 'jerseys/cbj-foligno-71.png', tier: 'emerald' },
    { name: 'Panarin — #9', image: 'jerseys/cbj-panarin-9.png', tier: 'emerald' },
    { name: 'Dubois — #18', image: 'jerseys/cbj-dubois-18.png', tier: 'emerald' },
    { name: 'Dubinsky — #17', image: 'jerseys/cbj-dubinsky-17.png', tier: 'emerald' },
    { name: 'Voracek — #93', image: 'jerseys/cbj-voracek-93.png', tier: 'emerald' },
    { name: 'Umberger — #20', image: 'jerseys/cbj-umberger-20.png', tier: 'gold' },
    { name: 'Vermette — #50', image: 'jerseys/cbj-vermette-50.png', tier: 'gold' },
    { name: 'Jenner — #38', image: 'jerseys/cbj-jenner-38.png', tier: 'gold' },
    { name: 'Bjorkstrand — #28', image: 'jerseys/cbj-bjorkstrand-28.png', tier: 'gold' },
    { name: 'Werenski — #8', image: 'jerseys/cbj-werenski-8.png', tier: 'gold' },
    { name: 'Laine — #29', image: 'jerseys/cbj-laine-29.png', tier: 'silver' },
    { name: 'Duchene — #95', image: 'jerseys/cbj-duchene-95.png', tier: 'silver' },
    { name: 'Brassard — #16', image: 'jerseys/cbj-brassard-16.png', tier: 'silver' },
    { name: 'Tyutin — #51', image: 'jerseys/cbj-tyutin-51.png', tier: 'silver' },
    { name: 'Johnson — #7', image: 'jerseys/cbj-johnson-7.png', tier: 'silver' },
  ],
  DAL: [
    { name: 'Modano — #9', image: 'jerseys/dal-modano-9.png', tier: 'amethyst' },
    { name: 'Nieuwendyk — #25', image: 'jerseys/dal-nieuwendyk-25.png', tier: 'amethyst' },
    { name: 'Hatcher — #2', image: 'jerseys/dal-hatcher-2.png', tier: 'ruby' },
    { name: 'Hull — #22', image: 'jerseys/dal-hull-22.png', tier: 'ruby' },
    { name: 'Zubov — #56', image: 'jerseys/dal-zubov-56.png', tier: 'ruby' },
    { name: 'Turco — #35', image: 'jerseys/dal-turco-35.png', tier: 'emerald' },
    { name: 'Lehtinen — #26', image: 'jerseys/dal-lehtinen-26.png', tier: 'emerald' },
    { name: 'Benn — #14', image: 'jerseys/dal-benn-14.png', tier: 'emerald' },
    { name: 'Morrow — #10', image: 'jerseys/dal-morrow-10.png', tier: 'emerald' },
    { name: 'Seguin — #91', image: 'jerseys/dal-seguin-91.png', tier: 'emerald' },
    { name: 'Heiskanen — #4', image: 'jerseys/dal-heiskanen-4.png', tier: 'gold' },
    { name: 'Klingberg — #3', image: 'jerseys/dal-klingberg-3.png', tier: 'gold' },
    { name: 'Carbonneau — #21', image: 'jerseys/dal-carbonneau-21.png', tier: 'gold' },
    { name: 'Sydor — #5', image: 'jerseys/dal-sydor-5.png', tier: 'gold' },
    { name: 'Sharp — #10', image: 'jerseys/dal-sharp-10.png', tier: 'gold' },
    { name: 'Radulov — #47', image: 'jerseys/dal-radulov-47.png', tier: 'silver' },
    { name: 'Hintz — #24', image: 'jerseys/dal-hintz-24.png', tier: 'silver' },
    { name: 'Robertson — #21', image: 'jerseys/dal-robertson-21.png', tier: 'silver' },
    { name: 'Lindell — #23', image: 'jerseys/dal-lindell-23.png', tier: 'silver' },
    { name: 'Pavelski — #16', image: 'jerseys/dal-pavelski-16.png', tier: 'silver' },
  ],
  DET: [
    { name: 'Howe — #19', image: 'jerseys/det-howe-19.png', tier: 'diamond' },
    { name: 'Howe — #2', image: 'jerseys/det-howe-2.png', tier: 'amethyst' },
    { name: 'Lidstrom — #5', image: 'jerseys/det-lidstrom-5.png', tier: 'ruby' },
    { name: 'Sawchuk — #1', image: 'jerseys/det-sawchuk-1.png', tier: 'ruby' },
    { name: 'Delvecchio — #10', image: 'jerseys/det-delvecchio-10.png', tier: 'ruby' },
    { name: 'Fedorov — #91', image: 'jerseys/det-fedorov-91.png', tier: 'emerald' },
    { name: 'Lindsay — #15', image: 'jerseys/det-lindsay-15.png', tier: 'emerald' },
    { name: 'Konstantinov — #16', image: 'jerseys/det-konstantinov-16.png', tier: 'emerald' },
    { name: 'Shanahan — #14', image: 'jerseys/det-shanahan-14.png', tier: 'emerald' },
    { name: 'Osgood — #30', image: 'jerseys/det-osgood-30.png', tier: 'emerald' },
    { name: 'Abel — #12', image: 'jerseys/det-abel-12.png', tier: 'gold' },
    { name: 'Kelly — #4', image: 'jerseys/det-kelly-4.png', tier: 'gold' },
    { name: 'Datsyuk — #13', image: 'jerseys/det-datsyuk-13.png', tier: 'gold' },
    { name: 'Zetterberg — #40', image: 'jerseys/det-zetterberg-40.png', tier: 'gold' },
    { name: 'Draper — #33', image: 'jerseys/det-draper-33.png', tier: 'gold' },
    { name: 'Probert — #24', image: 'jerseys/det-probert-24.png', tier: 'silver' },
    { name: 'Chelios — #24', image: 'jerseys/det-chelios-24.png', tier: 'silver' },
    { name: 'Holmstrom — #96', image: 'jerseys/det-holmstrom-96.png', tier: 'silver' },
    { name: 'Redmond — #20', image: 'jerseys/det-redmond-20.png', tier: 'silver' },
    { name: 'Gallant — #17', image: 'jerseys/det-gallant-17.png', tier: 'silver' },
  ],
  EDM: [
    { name: 'Gretzky — #99', image: 'jerseys/edm-gretzky-99.png', tier: 'diamond' },
    { name: 'Messier — #11', image: 'jerseys/edm-messier-11.png', tier: 'amethyst' },
    { name: 'Fuhr — #31', image: 'jerseys/edm-fuhr-31.png', tier: 'ruby' },
    { name: 'Coffey — #7', image: 'jerseys/edm-coffey-7.png', tier: 'ruby' },
    { name: 'Kurri — #17', image: 'jerseys/edm-kurri-17.png', tier: 'ruby' },
    { name: 'Lowe — #4', image: 'jerseys/edm-lowe-4.png', tier: 'emerald' },
    { name: 'Anderson — #9', image: 'jerseys/edm-anderson-9.png', tier: 'emerald' },
    { name: 'Tikkanen — #10', image: 'jerseys/edm-tikkanen-10.png', tier: 'emerald' },
    { name: 'McDavid — #97', image: 'jerseys/edm-mcdavid-97.png', tier: 'emerald' },
    { name: 'Bill Ranford — #30', image: 'jerseys/edm-bill-ranford-30.png', tier: 'emerald' },
    { name: 'Semenko — #16', image: 'jerseys/edm-semenko-16.png', tier: 'gold' },
    { name: 'Draisaitl — #29', image: 'jerseys/edm-draisaitl-29.png', tier: 'gold' },
    { name: 'Smyth — #94', image: 'jerseys/edm-smyth-94.png', tier: 'gold' },
    { name: 'Simpson — #18', image: 'jerseys/edm-simpson-18.png', tier: 'gold' },
    { name: 'Weight — #39', image: 'jerseys/edm-weight-39.png', tier: 'gold' },
    { name: 'Guerin — #13', image: 'jerseys/edm-guerin-13.png', tier: 'silver' },
    { name: 'MacTavish — #14', image: 'jerseys/edm-mactavish-14.png', tier: 'silver' },
    { name: 'Huddy — #22', image: 'jerseys/edm-huddy-22.png', tier: 'silver' },
    { name: 'Hamilton — #14', image: 'jerseys/edm-hamilton-14.png', tier: 'silver' },
    { name: 'Smith — #35', image: 'jerseys/edm-smith-35.png', tier: 'silver' },
  ],
  FLA: [
    { name: 'Luongo — #1', image: 'jerseys/fla-luongo-1.png', tier: 'amethyst' },
    { name: 'Barkov — #16', image: 'jerseys/fla-barkov-16.png', tier: 'amethyst' },
    { name: 'Vanbiesbrouck — #34', image: 'jerseys/fla-vanbiesbrouck-34.png', tier: 'ruby' },
    { name: 'Ekblad — #5', image: 'jerseys/fla-ekblad-5.png', tier: 'ruby' },
    { name: 'Jokinen — #12', image: 'jerseys/fla-jokinen-12.png', tier: 'ruby' },
    { name: 'Bure — #10', image: 'jerseys/fla-bure-10.png', tier: 'emerald' },
    { name: 'Weiss — #17', image: 'jerseys/fla-weiss-17.png', tier: 'emerald' },
    { name: 'Mellanby — #24', image: 'jerseys/fla-mellanby-24.png', tier: 'emerald' },
    { name: 'Huberdeau — #11', image: 'jerseys/fla-huberdeau-11.png', tier: 'emerald' },
    { name: 'Bobrovsky — #72', image: 'jerseys/fla-bobrovsky-72.png', tier: 'emerald' },
    { name: 'Dvorak — #18', image: 'jerseys/fla-dvorak-18.png', tier: 'gold' },
    { name: 'Trocheck — #21', image: 'jerseys/fla-trocheck-21.png', tier: 'gold' },
    { name: 'McCabe — #24', image: 'jerseys/fla-mccabe-24.png', tier: 'gold' },
    { name: 'Huselius — #20', image: 'jerseys/fla-huselius-20.png', tier: 'gold' },
    { name: 'Jovanovski — #55', image: 'jerseys/fla-jovanovski-55.png', tier: 'gold' },
    { name: 'Vokoun — #29', image: 'jerseys/fla-vokoun-29.png', tier: 'silver' },
    { name: 'Jagr — #68', image: 'jerseys/fla-jagr-68.png', tier: 'silver' },
    { name: 'Barnes — #11', image: 'jerseys/fla-barnes-11.png', tier: 'silver' },
    { name: 'Worrell — #16', image: 'jerseys/fla-worrell-16.png', tier: 'silver' },
    { name: 'Bouwmeester — #4', image: 'jerseys/fla-bouwmeester-4.png', tier: 'silver' },
  ],
  LAK: [
    { name: 'Gretzky — #99', image: 'jerseys/lak-gretzky-99.png', tier: 'diamond' },
    { name: 'Dionne — #16', image: 'jerseys/lak-dionne-16.png', tier: 'amethyst' },
    { name: 'Robitaille — #20', image: 'jerseys/lak-robitaille-20.png', tier: 'ruby' },
    { name: 'Vachon — #30', image: 'jerseys/lak-vachon-30.png', tier: 'ruby' },
    { name: 'Taylor — #18', image: 'jerseys/lak-taylor-18.png', tier: 'ruby' },
    { name: 'Simmer — #11', image: 'jerseys/lak-simmer-11.png', tier: 'emerald' },
    { name: 'Nicholls — #15', image: 'jerseys/lak-nicholls-15.png', tier: 'emerald' },
    { name: 'Blake — #4', image: 'jerseys/lak-blake-4.png', tier: 'emerald' },
    { name: 'Doughty — #8', image: 'jerseys/lak-doughty-8.png', tier: 'emerald' },
    { name: 'Quick — #32', image: 'jerseys/lak-quick-32.png', tier: 'emerald' },
    { name: 'Kopitar — #11', image: 'jerseys/lak-kopitar-11.png', tier: 'gold' },
    { name: 'Brown — #23', image: 'jerseys/lak-brown-23.png', tier: 'gold' },
    { name: 'Goring — #9', image: 'jerseys/lak-goring-9.png', tier: 'gold' },
    { name: 'Norstrom — #14', image: 'jerseys/lak-norstrom-14.png', tier: 'gold' },
    { name: 'Kurri — #17', image: 'jerseys/lak-kurri-17.png', tier: 'gold' },
    { name: 'Jim Fox — #20', image: 'jerseys/lak-jim-fox-20.png', tier: 'silver' },
    { name: 'Palffy — #33', image: 'jerseys/lak-palffy-33.png', tier: 'silver' },
    { name: 'Stoll — #28', image: 'jerseys/lak-stoll-28.png', tier: 'silver' },
    { name: 'Martinez — #27', image: 'jerseys/lak-martinez-27.png', tier: 'silver' },
    { name: 'Hrudey — #32', image: 'jerseys/lak-hrudey-32.png', tier: 'silver' },
  ],
  MIN: [
    { name: 'Gaborik — #10', image: 'jerseys/min-gaborik-10.png', tier: 'amethyst' },
    { name: 'Koivu — #9', image: 'jerseys/min-koivu-9.png', tier: 'amethyst' },
    { name: 'Backstrom — #35', image: 'jerseys/min-backstrom-35.png', tier: 'ruby' },
    { name: 'Parise — #11', image: 'jerseys/min-parise-11.png', tier: 'ruby' },
    { name: 'Suter — #20', image: 'jerseys/min-suter-20.png', tier: 'ruby' },
    { name: 'Roloson — #30', image: 'jerseys/min-roloson-30.png', tier: 'emerald' },
    { name: 'Brunette — #15', image: 'jerseys/min-brunette-15.png', tier: 'emerald' },
    { name: 'Burns — #8', image: 'jerseys/min-burns-8.png', tier: 'emerald' },
    { name: 'Harding — #37', image: 'jerseys/min-harding-37.png', tier: 'emerald' },
    { name: 'Spurgeon — #46', image: 'jerseys/min-spurgeon-46.png', tier: 'emerald' },
    { name: 'Granlund — #64', image: 'jerseys/min-granlund-64.png', tier: 'gold' },
    { name: 'Niederreiter — #22', image: 'jerseys/min-niederreiter-22.png', tier: 'gold' },
    { name: 'Zuccarello — #36', image: 'jerseys/min-zuccarello-36.png', tier: 'gold' },
    { name: 'Eriksson Ek — #14', image: 'jerseys/min-eriksson-ek-14.png', tier: 'gold' },
    { name: 'Brodin — #25', image: 'jerseys/min-brodin-25.png', tier: 'gold' },
    { name: 'Dubnyk — #40', image: 'jerseys/min-dubnyk-40.png', tier: 'silver' },
    { name: 'Fiala — #22', image: 'jerseys/min-fiala-22.png', tier: 'silver' },
    { name: 'Kaprizov — #97', image: 'jerseys/min-kaprizov-97.png', tier: 'silver' },
    { name: 'Middleton — #24', image: 'jerseys/min-middleton-24.png', tier: 'silver' },
    { name: 'Zucker — #16', image: 'jerseys/min-zucker-16.png', tier: 'silver' },
  ],
  MTL: [
    { name: 'Maurice Richard — #9', image: 'jerseys/mtl-maurice-richard-9.png', tier: 'diamond' },
    { name: 'Jean Beliveau — #4', image: 'jerseys/mtl-jean-beliveau-4.png', tier: 'diamond' },
    { name: 'Jacques Plante — #1', image: 'jerseys/mtl-jacques-plante-1.png', tier: 'ruby' },
    { name: 'Guy Lafleur — #10', image: 'jerseys/mtl-guy-lafleur-10.png', tier: 'ruby' },
    { name: 'Ken Dryden — #29', image: 'jerseys/mtl-ken-dryden-29.png', tier: 'ruby' },
    { name: 'Doug Harvey — #2', image: 'jerseys/mtl-doug-harvey-2.png', tier: 'emerald' },
    { name: 'Bernie Geoffrion — #5', image: 'jerseys/mtl-bernie-geoffrion-5.png', tier: 'emerald' },
    { name: 'Henri Richard — #16', image: 'jerseys/mtl-henri-richard-16.png', tier: 'emerald' },
    { name: 'Larry Robinson — #19', image: 'jerseys/mtl-larry-robinson-19.png', tier: 'emerald' },
    { name: 'Patrick Roy — #33', image: 'jerseys/mtl-patrick-roy-33.png', tier: 'emerald' },
    { name: 'Dickie Moore — #12', image: 'jerseys/mtl-dickie-moore-12.png', tier: 'gold' },
    { name: 'Howie Morenz — #7', image: 'jerseys/mtl-howie-morenz-7.png', tier: 'gold' },
    { name: 'Serge Savard — #18', image: 'jerseys/mtl-serge-savard-18.png', tier: 'gold' },
    { name: 'Toe Blake — #6', image: 'jerseys/mtl-toe-blake-6.png', tier: 'gold' },
    { name: 'Emile Bouchard — #3', image: 'jerseys/mtl-emile-bouchard-3.png', tier: 'gold' },
    { name: 'Carey Price — #31', image: 'jerseys/mtl-carey-price-31.png', tier: 'silver' },
    { name: 'Guy Lapointe — #5', image: 'jerseys/mtl-guy-lapointe-5.png', tier: 'silver' },
    { name: 'Bobby Rousseau — #15', image: 'jerseys/mtl-bobby-rousseau-15.png', tier: 'silver' },
    { name: 'Elmer Lach — #16', image: 'jerseys/mtl-elmer-lach-16.png', tier: 'silver' },
    { name: 'Saku Koivu — #11', image: 'jerseys/mtl-saku-koivu-11.png', tier: 'silver' },
  ],
  NSH: [
    { name: 'Rinne — #35', image: 'jerseys/nsh-rinne-35.png', tier: 'amethyst' },
    { name: 'Weber — #6', image: 'jerseys/nsh-weber-6.png', tier: 'amethyst' },
    { name: 'Josi — #59', image: 'jerseys/nsh-josi-59.png', tier: 'ruby' },
    { name: 'Forsberg — #9', image: 'jerseys/nsh-forsberg-9.png', tier: 'ruby' },
    { name: 'Ellis — #4', image: 'jerseys/nsh-ellis-4.png', tier: 'ruby' },
    { name: 'Vokoun — #29', image: 'jerseys/nsh-vokoun-29.png', tier: 'emerald' },
    { name: 'Arvidsson — #33', image: 'jerseys/nsh-arvidsson-33.png', tier: 'emerald' },
    { name: 'Granlund — #64', image: 'jerseys/nsh-granlund-64.png', tier: 'emerald' },
    { name: 'Smith — #15', image: 'jerseys/nsh-smith-15.png', tier: 'emerald' },
    { name: 'Ekholm — #14', image: 'jerseys/nsh-ekholm-14.png', tier: 'emerald' },
    { name: 'Legwand — #11', image: 'jerseys/nsh-legwand-11.png', tier: 'gold' },
    { name: 'Saros — #74', image: 'jerseys/nsh-saros-74.png', tier: 'gold' },
    { name: 'Suter — #20', image: 'jerseys/nsh-suter-20.png', tier: 'gold' },
    { name: 'Nash — #21', image: 'jerseys/nsh-nash-21.png', tier: 'gold' },
    { name: 'Bonino — #13', image: 'jerseys/nsh-bonino-13.png', tier: 'gold' },
    { name: 'Fisher — #12', image: 'jerseys/nsh-fisher-12.png', tier: 'silver' },
    { name: 'Fiala — #22', image: 'jerseys/nsh-fiala-22.png', tier: 'silver' },
    { name: 'Eberle — #7', image: 'jerseys/nsh-eberle-7.png', tier: 'silver' },
    { name: 'Kariya — #9', image: 'jerseys/nsh-kariya-9.png', tier: 'silver' },
    { name: 'Timonen — #44', image: 'jerseys/nsh-timonen-44.png', tier: 'silver' },
  ],
  NJD: [
    { name: 'Brodeur — #30', image: 'jerseys/njd-brodeur-30.png', tier: 'diamond' },
    { name: 'Stevens — #4', image: 'jerseys/njd-stevens-4.png', tier: 'amethyst' },
    { name: 'Elias — #26', image: 'jerseys/njd-elias-26.png', tier: 'ruby' },
    { name: 'Niedermayer — #27', image: 'jerseys/njd-niedermayer-27.png', tier: 'ruby' },
    { name: 'Maclean — #15', image: 'jerseys/njd-maclean-15.png', tier: 'ruby' },
    { name: 'Daneyko — #3', image: 'jerseys/njd-daneyko-3.png', tier: 'emerald' },
    { name: 'Gionta — #14', image: 'jerseys/njd-gionta-14.png', tier: 'emerald' },
    { name: 'Holik — #16', image: 'jerseys/njd-holik-16.png', tier: 'emerald' },
    { name: 'Hall — #9', image: 'jerseys/njd-hall-9.png', tier: 'emerald' },
    { name: 'Rafalski — #28', image: 'jerseys/njd-rafalski-28.png', tier: 'emerald' },
    { name: 'Langenbrunner — #15', image: 'jerseys/njd-langenbrunner-15.png', tier: 'gold' },
    { name: 'C. Lemieux — #22', image: 'jerseys/njd-c-lemieux-22.png', tier: 'gold' },
    { name: 'Richer — #44', image: 'jerseys/njd-richer-44.png', tier: 'gold' },
    { name: 'Gomez — #23', image: 'jerseys/njd-gomez-23.png', tier: 'gold' },
    { name: 'Pandolfo — #20', image: 'jerseys/njd-pandolfo-20.png', tier: 'gold' },
    { name: 'Shanahan — #11', image: 'jerseys/njd-shanahan-11.png', tier: 'silver' },
    { name: 'Brylin — #18', image: 'jerseys/njd-brylin-18.png', tier: 'silver' },
    { name: 'Driver — #23', image: 'jerseys/njd-driver-23.png', tier: 'silver' },
    { name: 'Henrique — #14', image: 'jerseys/njd-henrique-14.png', tier: 'silver' },
    { name: 'Terreri — #31', image: 'jerseys/njd-terreri-31.png', tier: 'silver' },
  ],
  NYI: [
    { name: 'Denis Potvin — #5', image: 'jerseys/nyi-denis-potvin-5.png', tier: 'amethyst' },
    { name: 'Mike Bossy — #22', image: 'jerseys/nyi-mike-bossy-22.png', tier: 'diamond' },
    { name: 'Bryan Trottier — #19', image: 'jerseys/nyi-bryan-trottier-19.png', tier: 'ruby' },
    { name: 'Billy Smith — #31', image: 'jerseys/nyi-billy-smith-31.png', tier: 'ruby' },
    { name: 'Clark Gillies — #9', image: 'jerseys/nyi-clark-gillies-9.png', tier: 'ruby' },
    { name: 'John Tonelli — #27', image: 'jerseys/nyi-john-tonelli-27.png', tier: 'emerald' },
    { name: 'Butch Goring — #91', image: 'jerseys/nyi-butch-goring-91.png', tier: 'emerald' },
    { name: 'Bob Nystrom — #23', image: 'jerseys/nyi-bob-nystrom-23.png', tier: 'emerald' },
    { name: 'Ken Morrow — #6', image: 'jerseys/nyi-ken-morrow-6.png', tier: 'emerald' },
    { name: 'Bob Bourne — #14', image: 'jerseys/nyi-bob-bourne-14.png', tier: 'emerald' },
    { name: 'Pat Lafontaine — #16', image: 'jerseys/nyi-pat-lafontaine-16.png', tier: 'gold' },
    { name: 'Pierre Turgeon — #77', image: 'jerseys/nyi-pierre-turgeon-77.png', tier: 'gold' },
    { name: 'Stefan Persson — #7', image: 'jerseys/nyi-stefan-persson-7.png', tier: 'gold' },
    { name: 'Chico Resch — #1', image: 'jerseys/nyi-chico-resch-1.png', tier: 'gold' },
    { name: 'Brent Sutter — #21', image: 'jerseys/nyi-brent-sutter-21.png', tier: 'gold' },
    { name: 'John Tavares — #91', image: 'jerseys/nyi-john-tavares-91.png', tier: 'silver' },
    { name: 'Mathew Barzal — #13', image: 'jerseys/nyi-mathew-barzal-13.png', tier: 'silver' },
    { name: 'Ilya Sorokin — #30', image: 'jerseys/nyi-ilya-sorokin-30.png', tier: 'silver' },
    { name: 'Kenny Jonsson — #29', image: 'jerseys/nyi-kenny-jonsson-29.png', tier: 'silver' },
    { name: 'Ziggy Palffy — #16', image: 'jerseys/nyi-ziggy-palffy-16.png', tier: 'silver' },
  ],
  NYR: [
    { name: 'Henrik Lundqvist — #30', image: 'jerseys/nyr-henrik-lundqvist-30.png', tier: 'amethyst' },
    { name: 'Brian Leetch — #2', image: 'jerseys/nyr-brian-leetch-2.png', tier: 'amethyst' },
    { name: 'Mark Messier — #11', image: 'jerseys/nyr-mark-messier-11.png', tier: 'diamond' },
    { name: 'Rod Gilbert — #7', image: 'jerseys/nyr-rod-gilbert-7.png', tier: 'ruby' },
    { name: 'Jean Ratelle — #19', image: 'jerseys/nyr-jean-ratelle-19.png', tier: 'ruby' },
    { name: 'Andy Bathgate — #9', image: 'jerseys/nyr-andy-bathgate-9.png', tier: 'emerald' },
    { name: 'Brad Park — #2', image: 'jerseys/nyr-brad-park-2.png', tier: 'emerald' },
    { name: 'Harry Howell — #3', image: 'jerseys/nyr-harry-howell-3.png', tier: 'emerald' },
    { name: 'Vic Hadfield — #11', image: 'jerseys/nyr-vic-hadfield-11.png', tier: 'emerald' },
    { name: 'Adam Graves — #9', image: 'jerseys/nyr-adam-graves-9.png', tier: 'emerald' },
    { name: 'Chris Kreider — #20', image: 'jerseys/nyr-chris-kreider-20.png', tier: 'gold' },
    { name: 'Ed Giacomin — #1', image: 'jerseys/nyr-ed-giacomin-1.png', tier: 'gold' },
    { name: 'Mike Richter — #35', image: 'jerseys/nyr-mike-richter-35.png', tier: 'gold' },
    { name: 'Ron Greschner — #4', image: 'jerseys/nyr-ron-greschner-4.png', tier: 'gold' },
    { name: 'Frank Boucher — #7', image: 'jerseys/nyr-frank-boucher-7.png', tier: 'gold' },
    { name: 'Bill Cook — #5', image: 'jerseys/nyr-bill-cook-5.png', tier: 'silver' },
    { name: 'Steve Vickers — #10', image: 'jerseys/nyr-steve-vickers-10.png', tier: 'silver' },
    { name: 'Walt Tkaczuk — #18', image: 'jerseys/nyr-walt-tkaczuk-18.png', tier: 'silver' },
    { name: 'Mika Zibanejad — #93', image: 'jerseys/nyr-mika-zibanejad-93.png', tier: 'silver' },
    { name: 'Gump Worsley — #1', image: 'jerseys/nyr-gump-worsley-1.png', tier: 'silver' },
  ],
  OTT: [
    { name: 'Daniel Alfredsson — #11', image: 'jerseys/ott-daniel-alfredsson-11.png', tier: 'amethyst' },
    { name: 'Wade Redden — #6', image: 'jerseys/ott-wade-redden-6.png', tier: 'amethyst' },
    { name: 'Jason Spezza — #19', image: 'jerseys/ott-jason-spezza-19.png', tier: 'ruby' },
    { name: 'Craig Anderson — #41', image: 'jerseys/ott-craig-anderson-41.png', tier: 'ruby' },
    { name: 'Chris Phillips — #4', image: 'jerseys/ott-chris-phillips-4.png', tier: 'ruby' },
    { name: 'Marian Hossa — #18', image: 'jerseys/ott-marian-hossa-18.png', tier: 'emerald' },
    { name: 'Radek Bonk — #14', image: 'jerseys/ott-radek-bonk-14.png', tier: 'emerald' },
    { name: 'Dany Heatley — #15', image: 'jerseys/ott-dany-heatley-15.png', tier: 'emerald' },
    { name: 'Zdeno Chara — #3', image: 'jerseys/ott-zdeno-chara-3.png', tier: 'emerald' },
    { name: 'Patrick Lalime — #31', image: 'jerseys/ott-patrick-lalime-31.png', tier: 'emerald' },
    { name: 'Mike Fisher — #12', image: 'jerseys/ott-mike-fisher-12.png', tier: 'gold' },
    { name: 'Milan Michalek — #9', image: 'jerseys/ott-milan-michalek-9.png', tier: 'gold' },
    { name: 'Chris Neil — #25', image: 'jerseys/ott-chris-neil-25.png', tier: 'gold' },
    { name: 'Erik Karlsson — #65', image: 'jerseys/ott-erik-karlsson-65.png', tier: 'gold' },
    { name: 'Brady Tkachuk — #7', image: 'jerseys/ott-brady-tkachuk-7.png', tier: 'gold' },
    { name: 'Tim Stutzle — #18', image: 'jerseys/ott-tim-stutzle-18.png', tier: 'silver' },
    { name: 'Claude Giroux — #28', image: 'jerseys/ott-claude-giroux-28.png', tier: 'silver' },
    { name: 'Thomas Chabot — #72', image: 'jerseys/ott-thomas-chabot-72.png', tier: 'silver' },
    { name: 'Anton Forsberg — #31', image: 'jerseys/ott-anton-forsberg-31.png', tier: 'silver' },
    { name: 'Mark Stone — #61', image: 'jerseys/ott-mark-stone-61.png', tier: 'silver' },
  ],
  PHI: [
    { name: 'Clarke — #16', image: 'jerseys/phi-clarke-16.png', tier: 'amethyst' },
    { name: 'Parent — #1', image: 'jerseys/phi-parent-1.png', tier: 'amethyst' },
    { name: 'Barber — #7', image: 'jerseys/phi-barber-7.png', tier: 'ruby' },
    { name: 'Lindros — #88', image: 'jerseys/phi-lindros-88.png', tier: 'ruby' },
    { name: 'Leclair — #10', image: 'jerseys/phi-leclair-10.png', tier: 'ruby' },
    { name: 'Recchi — #8', image: 'jerseys/phi-recchi-8.png', tier: 'emerald' },
    { name: 'Leach — #27', image: 'jerseys/phi-leach-27.png', tier: 'emerald' },
    { name: 'MacLeish — #19', image: 'jerseys/phi-macleish-19.png', tier: 'emerald' },
    { name: 'Brind\'Amour — #17', image: 'jerseys/phi-brind-amour-17.png', tier: 'emerald' },
    { name: 'Timonen — #44', image: 'jerseys/phi-timonen-44.png', tier: 'emerald' },
    { name: 'Hextall — #27', image: 'jerseys/phi-hextall-27.png', tier: 'gold' },
    { name: 'Lindbergh — #31', image: 'jerseys/phi-lindbergh-31.png', tier: 'gold' },
    { name: 'Gagne — #12', image: 'jerseys/phi-gagne-12.png', tier: 'gold' },
    { name: 'Richards — #18', image: 'jerseys/phi-richards-18.png', tier: 'gold' },
    { name: 'Giroux — #28', image: 'jerseys/phi-giroux-28.png', tier: 'gold' },
    { name: 'Simmonds — #17', image: 'jerseys/phi-simmonds-17.png', tier: 'silver' },
    { name: 'Voracek — #93', image: 'jerseys/phi-voracek-93.png', tier: 'silver' },
    { name: 'Couturier — #14', image: 'jerseys/phi-couturier-14.png', tier: 'silver' },
    { name: 'Hartnell — #19', image: 'jerseys/phi-hartnell-19.png', tier: 'silver' },
    { name: 'Poulin — #20', image: 'jerseys/phi-poulin-20.png', tier: 'silver' },
  ],
  PIT: [
    { name: 'Lemieux — #66', image: 'jerseys/pit-lemieux-66.png', tier: 'diamond' },
    { name: 'Barrasso — #35', image: 'jerseys/pit-barrasso-35.png', tier: 'amethyst' },
    { name: 'Crosby — #87', image: 'jerseys/pit-crosby-87.png', tier: 'ruby' },
    { name: 'Malkin — #71', image: 'jerseys/pit-malkin-71.png', tier: 'ruby' },
    { name: 'Jagr — #68', image: 'jerseys/pit-jagr-68.png', tier: 'ruby' },
    { name: 'Francis — #10', image: 'jerseys/pit-francis-10.png', tier: 'emerald' },
    { name: 'Coffey — #77', image: 'jerseys/pit-coffey-77.png', tier: 'emerald' },
    { name: 'Stevens — #12', image: 'jerseys/pit-stevens-12.png', tier: 'emerald' },
    { name: 'Zubov — #56', image: 'jerseys/pit-zubov-56.png', tier: 'emerald' },
    { name: 'Orpik — #44', image: 'jerseys/pit-orpik-44.png', tier: 'emerald' },
    { name: 'Fleury — #29', image: 'jerseys/pit-fleury-29.png', tier: 'gold' },
    { name: 'Murray — #30', image: 'jerseys/pit-murray-30.png', tier: 'gold' },
    { name: 'Mullen — #7', image: 'jerseys/pit-mullen-7.png', tier: 'gold' },
    { name: 'Jordan Staal — #11', image: 'jerseys/pit-jordan-staal-11.png', tier: 'gold' },
    { name: 'Trottier — #19', image: 'jerseys/pit-trottier-19.png', tier: 'gold' },
    { name: 'Guentzel — #59', image: 'jerseys/pit-guentzel-59.png', tier: 'silver' },
    { name: 'Hornqvist — #72', image: 'jerseys/pit-hornqvist-72.png', tier: 'silver' },
    { name: 'Kunitz — #14', image: 'jerseys/pit-kunitz-14.png', tier: 'silver' },
    { name: 'Recchi — #8', image: 'jerseys/pit-recchi-8.png', tier: 'silver' },
    { name: 'Letang — #58', image: 'jerseys/pit-letang-58.png', tier: 'silver' },
  ],
  SJS: [
    { name: 'Marleau — #12', image: 'jerseys/sjs-marleau-12.png', tier: 'amethyst' },
    { name: 'Thornton — #19', image: 'jerseys/sjs-thornton-19.png', tier: 'amethyst' },
    { name: 'Couture — #39', image: 'jerseys/sjs-couture-39.png', tier: 'ruby' },
    { name: 'Pavelski — #8', image: 'jerseys/sjs-pavelski-8.png', tier: 'ruby' },
    { name: 'Nolan — #11', image: 'jerseys/sjs-nolan-11.png', tier: 'ruby' },
    { name: 'Burns — #88', image: 'jerseys/sjs-burns-88.png', tier: 'emerald' },
    { name: 'Boyle — #22', image: 'jerseys/sjs-boyle-22.png', tier: 'emerald' },
    { name: 'Cheechoo — #14', image: 'jerseys/sjs-cheechoo-14.png', tier: 'emerald' },
    { name: 'Michalek — #9', image: 'jerseys/sjs-michalek-9.png', tier: 'emerald' },
    { name: 'Nabokov — #20', image: 'jerseys/sjs-nabokov-20.png', tier: 'emerald' },
    { name: 'Jones — #31', image: 'jerseys/sjs-jones-31.png', tier: 'gold' },
    { name: 'Hertl — #48', image: 'jerseys/sjs-hertl-48.png', tier: 'gold' },
    { name: 'Vlasic — #44', image: 'jerseys/sjs-vlasic-44.png', tier: 'gold' },
    { name: 'Ozolinsh — #8', image: 'jerseys/sjs-ozolinsh-8.png', tier: 'gold' },
    { name: 'Friesen — #16', image: 'jerseys/sjs-friesen-16.png', tier: 'gold' },
    { name: 'Irbe — #32', image: 'jerseys/sjs-irbe-32.png', tier: 'silver' },
    { name: 'Ricci — #17', image: 'jerseys/sjs-ricci-17.png', tier: 'silver' },
    { name: 'Stuart — #6', image: 'jerseys/sjs-stuart-6.png', tier: 'silver' },
    { name: 'Setoguchi — #13', image: 'jerseys/sjs-setoguchi-13.png', tier: 'silver' },
    { name: 'Karlsson — #65', image: 'jerseys/sjs-karlsson-65.png', tier: 'silver' },
  ],
  SEA: [
    { name: 'Eberle — #7', image: 'jerseys/sea-eberle-7.png', tier: 'amethyst' },
    { name: 'McCann — #19', image: 'jerseys/sea-mccann-19.png', tier: 'amethyst' },
    { name: 'Beniers — #10', image: 'jerseys/sea-beniers-10.png', tier: 'ruby' },
    { name: 'Gourde — #37', image: 'jerseys/sea-gourde-37.png', tier: 'ruby' },
    { name: 'Schwartz — #17', image: 'jerseys/sea-schwartz-17.png', tier: 'ruby' },
    { name: 'Dunn — #29', image: 'jerseys/sea-dunn-29.png', tier: 'emerald' },
    { name: 'Larsson — #6', image: 'jerseys/sea-larsson-6.png', tier: 'emerald' },
    { name: 'Bjorkstrand — #22', image: 'jerseys/sea-bjorkstrand-22.png', tier: 'emerald' },
    { name: 'Wennberg — #10', image: 'jerseys/sea-wennberg-10.png', tier: 'emerald' },
    { name: 'Grubauer — #31', image: 'jerseys/sea-grubauer-31.png', tier: 'emerald' },
    { name: 'Daccord — #35', image: 'jerseys/sea-daccord-35.png', tier: 'gold' },
    { name: 'Wright — #51', image: 'jerseys/sea-wright-51.png', tier: 'gold' },
    { name: 'Tanev — #13', image: 'jerseys/sea-tanev-13.png', tier: 'gold' },
    { name: 'Schultz — #4', image: 'jerseys/sea-schultz-4.png', tier: 'gold' },
    { name: 'Oleksiak — #24', image: 'jerseys/sea-oleksiak-24.png', tier: 'gold' },
    { name: 'Borgen — #3', image: 'jerseys/sea-borgen-3.png', tier: 'silver' },
    { name: 'Soucy — #28', image: 'jerseys/sea-soucy-28.png', tier: 'silver' },
    { name: 'Fleury — #41', image: 'jerseys/sea-fleury-41.png', tier: 'silver' },
    { name: 'Driedger — #60', image: 'jerseys/sea-driedger-60.png', tier: 'silver' },
    { name: 'Jones — #30', image: 'jerseys/sea-jones-30.png', tier: 'silver' },
  ],
  STL: [
    { name: 'Hull — #16', image: 'jerseys/stl-hull-16.png', tier: 'amethyst' },
    { name: 'Pronger — #44', image: 'jerseys/stl-pronger-44.png', tier: 'amethyst' },
    { name: 'B. Sutter — #11', image: 'jerseys/stl-b-sutter-11.png', tier: 'ruby' },
    { name: 'Oates — #12', image: 'jerseys/stl-oates-12.png', tier: 'ruby' },
    { name: 'Oates — #19', image: 'jerseys/stl-oates-19.png', tier: 'ruby' },
    { name: 'Federko — #24', image: 'jerseys/stl-federko-24.png', tier: 'emerald' },
    { name: 'Tarasenko — #91', image: 'jerseys/stl-tarasenko-91.png', tier: 'emerald' },
    { name: 'Berenson — #7', image: 'jerseys/stl-berenson-7.png', tier: 'emerald' },
    { name: 'Kariya — #9', image: 'jerseys/stl-kariya-9.png', tier: 'emerald' },
    { name: 'Chase — #22', image: 'jerseys/stl-chase-22.png', tier: 'emerald' },
    { name: 'MacInnis — #2', image: 'jerseys/stl-macinnis-2.png', tier: 'gold' },
    { name: 'O\'Reilly — #90', image: 'jerseys/stl-o-reilly-90.png', tier: 'gold' },
    { name: 'Hall — #19', image: 'jerseys/stl-hall-19.png', tier: 'gold' },
    { name: 'Chase — #77', image: 'jerseys/stl-chase-77.png', tier: 'gold' },
    { name: 'Weight — #39', image: 'jerseys/stl-weight-39.png', tier: 'gold' },
    { name: 'Pietrangelo — #27', image: 'jerseys/stl-pietrangelo-27.png', tier: 'silver' },
    { name: 'Binnington — #50', image: 'jerseys/stl-binnington-50.png', tier: 'silver' },
    { name: 'Joseph — #31', image: 'jerseys/stl-joseph-31.png', tier: 'silver' },
    { name: 'Demitra — #38', image: 'jerseys/stl-demitra-38.png', tier: 'silver' },
    { name: 'Tkachuk — #7', image: 'jerseys/stl-tkachuk-7.png', tier: 'silver' },
  ],
  TBL: [
    { name: 'Martin St. Louis — #26', image: 'jerseys/tbl-martin-st-louis-26.png', tier: 'amethyst' },
    { name: 'Victor Hedman — #77', image: 'jerseys/tbl-victor-hedman-77.png', tier: 'amethyst' },
    { name: 'Ondrej Palat — #18', image: 'jerseys/tbl-ondrej-palat-18.png', tier: 'ruby' },
    { name: 'Vincent Lecavalier — #4', image: 'jerseys/tbl-vincent-lecavalier-4.png', tier: 'ruby' },
    { name: 'Steven Stamkos — #91', image: 'jerseys/tbl-steven-stamkos-91.png', tier: 'ruby' },
    { name: 'Brayden Point — #21', image: 'jerseys/tbl-brayden-point-21.png', tier: 'emerald' },
    { name: 'Nikita Kucherov — #86', image: 'jerseys/tbl-nikita-kucherov-86.png', tier: 'emerald' },
    { name: 'Brad Bradley — #19', image: 'jerseys/tbl-brad-bradley-19.png', tier: 'emerald' },
    { name: 'Alex Killorn — #17', image: 'jerseys/tbl-alex-killorn-17.png', tier: 'emerald' },
    { name: 'Ruslan Fedotenko — #11', image: 'jerseys/tbl-ruslan-fedotenko-11.png', tier: 'emerald' },
    { name: 'Pavel Kubina — #73', image: 'jerseys/tbl-pavel-kubina-73.png', tier: 'gold' },
    { name: 'Tyler Johnson — #9', image: 'jerseys/tbl-tyler-johnson-9.png', tier: 'gold' },
    { name: 'Ben Bishop — #30', image: 'jerseys/tbl-ben-bishop-30.png', tier: 'gold' },
    { name: 'Yanni Gourde — #37', image: 'jerseys/tbl-yanni-gourde-37.png', tier: 'gold' },
    { name: 'Anthony Cirelli — #71', image: 'jerseys/tbl-anthony-cirelli-71.png', tier: 'gold' },
    { name: 'Dan Boyle — #22', image: 'jerseys/tbl-dan-boyle-22.png', tier: 'silver' },
    { name: 'Nikolai Khabibulin — #35', image: 'jerseys/tbl-nikolai-khabibulin-35.png', tier: 'silver' },
    { name: 'Andrei Vasilevskiy — #88', image: 'jerseys/tbl-andrei-vasilevskiy-88.png', tier: 'silver' },
    { name: 'Brad Richards — #19', image: 'jerseys/tbl-brad-richards-19.png', tier: 'silver' },
    { name: 'Fredrik Modin — #33', image: 'jerseys/tbl-fredrik-modin-33.png', tier: 'silver' },
  ],
  TOR: [
    { name: 'Mats Sundin — #13', image: 'jerseys/tor-mats-sundin-13.png', tier: 'amethyst' },
    { name: 'Borje Salming — #21', image: 'jerseys/tor-borje-salming-21.png', tier: 'amethyst' },
    { name: 'Wendel Clark — #17', image: 'jerseys/tor-wendel-clark-17.png', tier: 'ruby' },
    { name: 'Dave Keon — #14', image: 'jerseys/tor-dave-keon-14.png', tier: 'ruby' },
    { name: 'Darryl Sittler — #27', image: 'jerseys/tor-darryl-sittler-27.png', tier: 'ruby' },
    { name: 'Doug Gilmour — #93', image: 'jerseys/tor-doug-gilmour-93.png', tier: 'emerald' },
    { name: 'Lanny McDonald — #7', image: 'jerseys/tor-lanny-mcdonald-7.png', tier: 'emerald' },
    { name: 'Syl Apps — #10', image: 'jerseys/tor-syl-apps-10.png', tier: 'emerald' },
    { name: 'Gary Roberts — #7', image: 'jerseys/tor-gary-roberts-7.png', tier: 'emerald' },
    { name: 'Charlie Conacher — #1', image: 'jerseys/tor-charlie-conacher-1.png', tier: 'emerald' },
    { name: 'Tim Horton — #7', image: 'jerseys/tor-tim-horton-7.png', tier: 'gold' },
    { name: 'Ted Kennedy — #9', image: 'jerseys/tor-ted-kennedy-9.png', tier: 'gold' },
    { name: 'Johnny Bower — #1', image: 'jerseys/tor-johnny-bower-1.png', tier: 'gold' },
    { name: 'Auston Matthews — #34', image: 'jerseys/tor-auston-matthews-34.png', tier: 'gold' },
    { name: 'Mitch Marner — #16', image: 'jerseys/tor-mitch-marner-16.png', tier: 'gold' },
    { name: 'Tomas Kaberle — #15', image: 'jerseys/tor-tomas-kaberle-15.png', tier: 'silver' },
    { name: 'Felix Potvin — #29', image: 'jerseys/tor-felix-potvin-29.png', tier: 'silver' },
    { name: 'Ed Belfour — #30', image: 'jerseys/tor-ed-belfour-30.png', tier: 'silver' },
    { name: 'George Armstrong — #10', image: 'jerseys/tor-george-armstrong-10.png', tier: 'silver' },
    { name: 'Morgan Rielly — #44', image: 'jerseys/tor-morgan-rielly-44.png', tier: 'silver' },
  ],
  VAN: [
    { name: 'Henrik Sedin — #33', image: 'jerseys/van-henrik-sedin-33.png', tier: 'amethyst' },
    { name: 'Mattias Ohlund — #2', image: 'jerseys/van-mattias-ohlund-2.png', tier: 'amethyst' },
    { name: 'Daniel Sedin — #22', image: 'jerseys/van-daniel-sedin-22.png', tier: 'ruby' },
    { name: 'Trevor Linden — #16', image: 'jerseys/van-trevor-linden-16.png', tier: 'ruby' },
    { name: 'Thomas Gradin — #23', image: 'jerseys/van-thomas-gradin-23.png', tier: 'ruby' },
    { name: 'Markus Naslund — #19', image: 'jerseys/van-markus-naslund-19.png', tier: 'emerald' },
    { name: 'Stan Smyl — #12', image: 'jerseys/van-stan-smyl-12.png', tier: 'emerald' },
    { name: 'Jyrki Lumme — #6', image: 'jerseys/van-jyrki-lumme-6.png', tier: 'emerald' },
    { name: 'Alex Burrows — #14', image: 'jerseys/van-alex-burrows-14.png', tier: 'emerald' },
    { name: 'Tony Conacher — #9', image: 'jerseys/van-tony-conacher-9.png', tier: 'emerald' },
    { name: 'Dan Hamhuis — #2', image: 'jerseys/van-dan-hamhuis-2.png', tier: 'gold' },
    { name: 'Todd Bertuzzi — #44', image: 'jerseys/van-todd-bertuzzi-44.png', tier: 'gold' },
    { name: 'Kirk McLean — #1', image: 'jerseys/van-kirk-mclean-1.png', tier: 'gold' },
    { name: 'Bo Horvat — #53', image: 'jerseys/van-bo-horvat-53.png', tier: 'gold' },
    { name: 'Pavel Bure — #10', image: 'jerseys/van-pavel-bure-10.png', tier: 'gold' },
    { name: 'Ed Jovanovski — #55', image: 'jerseys/van-ed-jovanovski-55.png', tier: 'silver' },
    { name: 'Richard Brodeur — #35', image: 'jerseys/van-richard-brodeur-35.png', tier: 'silver' },
    { name: 'Roberto Luongo — #1', image: 'jerseys/van-roberto-luongo-1.png', tier: 'silver' },
    { name: 'Petri Skriko — #11', image: 'jerseys/van-petri-skriko-11.png', tier: 'silver' },
    { name: 'Alexander Mogilny — #89', image: 'jerseys/van-alexander-mogilny-89.png', tier: 'silver' },
  ],
  VGK: [
    { name: 'Fleury — #29', image: 'jerseys/vgk-fleury-29.png', tier: 'amethyst' },
    { name: 'Karlsson — #71', image: 'jerseys/vgk-karlsson-71.png', tier: 'amethyst' },
    { name: 'Marchessault — #81', image: 'jerseys/vgk-marchessault-81.png', tier: 'ruby' },
    { name: 'Smith — #19', image: 'jerseys/vgk-smith-19.png', tier: 'ruby' },
    { name: 'Pietrangelo — #7', image: 'jerseys/vgk-pietrangelo-7.png', tier: 'ruby' },
    { name: 'Theodore — #27', image: 'jerseys/vgk-theodore-27.png', tier: 'emerald' },
    { name: 'Stone — #61', image: 'jerseys/vgk-stone-61.png', tier: 'emerald' },
    { name: 'Pacioretty — #67', image: 'jerseys/vgk-pacioretty-67.png', tier: 'emerald' },
    { name: 'McNabb — #3', image: 'jerseys/vgk-mcnabb-3.png', tier: 'emerald' },
    { name: 'Eichel — #9', image: 'jerseys/vgk-eichel-9.png', tier: 'emerald' },
    { name: 'Stephenson — #20', image: 'jerseys/vgk-stephenson-20.png', tier: 'gold' },
    { name: 'Carrier — #28', image: 'jerseys/vgk-carrier-28.png', tier: 'gold' },
    { name: 'Martinez — #23', image: 'jerseys/vgk-martinez-23.png', tier: 'gold' },
    { name: 'Hill — #33', image: 'jerseys/vgk-hill-33.png', tier: 'gold' },
    { name: 'Kolesar — #55', image: 'jerseys/vgk-kolesar-55.png', tier: 'gold' },
    { name: 'Barbashev — #49', image: 'jerseys/vgk-barbashev-49.png', tier: 'silver' },
    { name: 'Schmidt — #88', image: 'jerseys/vgk-schmidt-88.png', tier: 'silver' },
    { name: 'Roy — #10', image: 'jerseys/vgk-roy-10.png', tier: 'silver' },
    { name: 'Howden — #21', image: 'jerseys/vgk-howden-21.png', tier: 'silver' },
    { name: 'Hague — #14', image: 'jerseys/vgk-hague-14.png', tier: 'silver' },
  ],
  WSH: [
    { name: 'Kolzig — #37', image: 'jerseys/wsh-kolzig-37.png', tier: 'amethyst' },
    { name: 'Ovechkin — #8', image: 'jerseys/wsh-ovechkin-8.png', tier: 'diamond' },
    { name: 'Backstrom — #19', image: 'jerseys/wsh-backstrom-19.png', tier: 'ruby' },
    { name: 'Bondra — #12', image: 'jerseys/wsh-bondra-12.png', tier: 'ruby' },
    { name: 'Johansson — #6', image: 'jerseys/wsh-johansson-6.png', tier: 'ruby' },
    { name: 'Holtby — #70', image: 'jerseys/wsh-holtby-70.png', tier: 'emerald' },
    { name: 'Kuznetsov — #92', image: 'jerseys/wsh-kuznetsov-92.png', tier: 'emerald' },
    { name: 'Carlson — #74', image: 'jerseys/wsh-carlson-74.png', tier: 'emerald' },
    { name: 'Gartner — #11', image: 'jerseys/wsh-gartner-11.png', tier: 'emerald' },
    { name: 'Hunter — #32', image: 'jerseys/wsh-hunter-32.png', tier: 'emerald' },
    { name: 'Langway — #5', image: 'jerseys/wsh-langway-5.png', tier: 'gold' },
    { name: 'Gonchar — #55', image: 'jerseys/wsh-gonchar-55.png', tier: 'gold' },
    { name: 'Laich — #21', image: 'jerseys/wsh-laich-21.png', tier: 'gold' },
    { name: 'Khristich — #25', image: 'jerseys/wsh-khristich-25.png', tier: 'gold' },
    { name: 'Miller — #10', image: 'jerseys/wsh-miller-10.png', tier: 'gold' },
    { name: 'Green — #52', image: 'jerseys/wsh-green-52.png', tier: 'silver' },
    { name: 'Walter — #18', image: 'jerseys/wsh-walter-18.png', tier: 'silver' },
    { name: 'Oshie — #77', image: 'jerseys/wsh-oshie-77.png', tier: 'silver' },
    { name: 'Murphy — #16', image: 'jerseys/wsh-murphy-16.png', tier: 'silver' },
    { name: 'Stevens — #4', image: 'jerseys/wsh-stevens-4.png', tier: 'silver' },
  ],
  WPG: [
    { name: 'Hellebuyck — #37', image: 'jerseys/wpg-hellebuyck-37.png', tier: 'amethyst' },
    { name: 'Wheeler — #26', image: 'jerseys/wpg-wheeler-26.png', tier: 'amethyst' },
    { name: 'Scheifele — #55', image: 'jerseys/wpg-scheifele-55.png', tier: 'ruby' },
    { name: 'Selanne — #13', image: 'jerseys/wpg-selanne-13.png', tier: 'ruby' },
    { name: 'Numminen — #27', image: 'jerseys/wpg-numminen-27.png', tier: 'ruby' },
    { name: 'Pavelec — #31', image: 'jerseys/wpg-pavelec-31.png', tier: 'emerald' },
    { name: 'Connor — #81', image: 'jerseys/wpg-connor-81.png', tier: 'emerald' },
    { name: 'Byfuglien — #33', image: 'jerseys/wpg-byfuglien-33.png', tier: 'emerald' },
    { name: 'Laine — #29', image: 'jerseys/wpg-laine-29.png', tier: 'emerald' },
    { name: 'Little — #18', image: 'jerseys/wpg-little-18.png', tier: 'emerald' },
    { name: 'Morrissey — #44', image: 'jerseys/wpg-morrissey-44.png', tier: 'gold' },
    { name: 'Housley — #22', image: 'jerseys/wpg-housley-22.png', tier: 'gold' },
    { name: 'Hawerchuk — #10', image: 'jerseys/wpg-hawerchuk-10.png', tier: 'gold' },
    { name: 'Ladd — #16', image: 'jerseys/wpg-ladd-16.png', tier: 'gold' },
    { name: 'Perreault — #85', image: 'jerseys/wpg-perreault-85.png', tier: 'gold' },
    { name: 'Trouba — #8', image: 'jerseys/wpg-trouba-8.png', tier: 'silver' },
    { name: 'Enstrom — #39', image: 'jerseys/wpg-enstrom-39.png', tier: 'silver' },
    { name: 'Lowry — #17', image: 'jerseys/wpg-lowry-17.png', tier: 'silver' },
    { name: 'Maclean — #19', image: 'jerseys/wpg-maclean-19.png', tier: 'silver' },
    { name: 'Stastny — #25', image: 'jerseys/wpg-stastny-25.png', tier: 'silver' },
  ],
};
